# Gozlem ve Değişken Secimi
## loc & iloc

In [12]:
import pandas as pd
import numpy as np

m = np.random.randint(1,30, size=(10,3))
df = pd.DataFrame(m,columns=["var1","var2","var3"])
df

   var1  var2  var3
0    28    24    29
1    22    29     8
2    23     8    28
3     2    13    21
4    17     1    12
5    12    17    22
6    24    16    25
7    15     8    27
8     4    27    27
9    23    18     1

In [14]:
# loc: tanımlandıgı seklıyle secim yapmak icin kullanılır
df.loc[0:3]
# index lemede 3 de alır 3 dahil

   var1  var2  var3
0    28    24    29
1    22    29     8
2    23     8    28
3     2    13    21

In [16]:
#iloc : alısık oldugumuz indeksleme mantıgı ile secim yapar
df.iloc[0:3] # index lemede 3 almaz 3 e kadar

   var1  var2  var3
0    28    24    29
1    22    29     8
2    23     8    28

In [20]:
df

   var1  var2  var3
0    28    24    29
1    22    29     8
2    23     8    28
3     2    13    21
4    17     1    12
5    12    17    22
6    24    16    25
7    15     8    27
8     4    27    27
9    23    18     1

In [26]:
df.iloc[0,0]

28

In [30]:
df.iloc[0:3,2:]

   var3
0    29
1     8
2    28

In [32]:
df

   var1  var2  var3
0    28    24    29
1    22    29     8
2    23     8    28
3     2    13    21
4    17     1    12
5    12    17    22
6    24    16    25
7    15     8    27
8     4    27    27
9    23    18     1

In [34]:
df.loc[0:3,"var3"]

0    29
1     8
2    28
3    21
Name: var3, dtype: int32

In [40]:
df.iloc[0:3]["var3"]

0    29
1     8
2    28
Name: var3, dtype: int32

In [42]:
# Kosullu Eleman işlemleri
import pandas as pd
import numpy as np

m = np.random.randint(1,30, size=(10,3))
df = pd.DataFrame(m,columns=["var1","var2","var3"])
df

   var1  var2  var3
0    29    23    19
1    25    25     7
2    20    11    14
3     2    23    14
4    28    29     6
5     1    11    26
6    16     3     3
7    27     3    21
8    25    25     1
9    24    24     9

In [44]:
df["var1"]

0    29
1    25
2    20
3     2
4    28
5     1
6    16
7    27
8    25
9    24
Name: var1, dtype: int32

In [46]:
df[0:2]

   var1  var2  var3
0    29    23    19
1    25    25     7

In [48]:
df[0:2]["var3"]

0    19
1     7
Name: var3, dtype: int32

In [52]:
df[0:2][["var1","var2"]]

   var1  var2
0    29    23
1    25    25

In [54]:
df

   var1  var2  var3
0    29    23    19
1    25    25     7
2    20    11    14
3     2    23    14
4    28    29     6
5     1    11    26
6    16     3     3
7    27     3    21
8    25    25     1
9    24    24     9

In [58]:
df.var1

0    29
1    25
2    20
3     2
4    28
5     1
6    16
7    27
8    25
9    24
Name: var1, dtype: int32

In [70]:
df[df.var1 > 15 ]

   var1  var2  var3
0    29    23    19
1    25    25     7
2    20    11    14
4    28    29     6
6    16     3     3
7    27     3    21
8    25    25     1
9    24    24     9

In [72]:
df[df.var1 > 15 ]["var1"]

0    29
1    25
2    20
4    28
6    16
7    27
8    25
9    24
Name: var1, dtype: int32

In [74]:
df

   var1  var2  var3
0    29    23    19
1    25    25     7
2    20    11    14
3     2    23    14
4    28    29     6
5     1    11    26
6    16     3     3
7    27     3    21
8    25    25     1
9    24    24     9

In [78]:
df[(df.var1 >15) & (df.var3<5)]

   var1  var2  var3
6    16     3     3
8    25    25     1

# Birleştirme (Join) İşlemleri

In [87]:
import numpy as np
import pandas as pd

m = np.random.randint(1,30,size=(5,3))
df1 = pd.DataFrame(m,columns = ["var1","var2","var3"])
df1

   var1  var2  var3
0     9    22    27
1     2     8    23
2    15    25    21
3     5    10    17
4     2    19     4

In [91]:
df2 = df1 + 99
df2

   var1  var2  var3
0   108   121   126
1   101   107   122
2   114   124   120
3   104   109   116
4   101   118   103

In [95]:
pd.concat([df1,df2]) # index lerde 0 dan baslar her liste icin

   var1  var2  var3
0     9    22    27
1     2     8    23
2    15    25    21
3     5    10    17
4     2    19     4
0   108   121   126
1   101   107   122
2   114   124   120
3   104   109   116
4   101   118   103

In [105]:
# index leri birleştirme
?pd.concat

Signature:
pd.concat(
    objs: 'Iterable[Series | DataFrame] | Mapping[HashableT, Series | DataFrame]',
    *,
    axis: 'Axis' = 0,
    join: 'str' = 'outer',
    ignore_index: 'bool' = False,
    keys: 'Iterable[Hashable] | None' = None,
    levels=None,
    names: 'list[HashableT] | None' = None,
    verify_integrity: 'bool' = False,
    sort: 'bool' = False,
    copy: 'bool | None' = None,
) -> 'DataFrame | Series'
Docstring:
Concatenate pandas objects along a particular axis.

Allows optional set logic along the other axes.

Can also add a layer of hierarchical indexing on the concatenation axis,
which may be useful if the labels are the same (or overlapping) on
the passed axis number.

Parameters
----------
objs : a sequence or mapping of Series or DataFrame objects
    If a mapping is passed, the sorted keys will be used as the `keys`
    argument, unless it is passed, in which case the values will be
    selected (see below). Any None objects will be dropped silently unless
    they are all None in which case a ValueError will be raised.
axis : {0/'index', 1/'columns'}, default 0
    The axis to concatenate along.
join : {'inner', 'outer'}, default 'outer'
    How to handle indexes on other axis (or axes).
ignore_index : bool, default False
    If True, do not use the index values along the concatenation axis. The
    resulting axis will be labeled 0, ..., n - 1. This is useful if you are
    concatenating objects where the concatenation axis does not have
    meaningful indexing information. Note the index values on the other
    axes are still respected in the join.
keys : sequence, default None
    If multiple levels passed, should contain tuples. Construct
    hierarchical index using the passed keys as the outermost level.
levels : list of sequences, default None
    Specific levels (unique values) to use for constructing a
    MultiIndex. Otherwise they will be inferred from the keys.
names : list, default None
    Names for the levels in the resulting hierarchical index.
verify_integrity : bool, default False
    Check whether the new concatenated axis contains duplicates. This can
    be very expensive relative to the actual data concatenation.
sort : bool, default False
    Sort non-concatenation axis if it is not already aligned. One exception to
    this is when the non-concatentation axis is a DatetimeIndex and join='outer'
    and the axis is not already aligned. In that case, the non-concatenation
    axis is always sorted lexicographically.
copy : bool, default True
    If False, do not copy data unnecessarily.

Returns
-------
object, type of objs
    When concatenating all ``Series`` along the index (axis=0), a
    ``Series`` is returned. When ``objs`` contains at least one
    ``DataFrame``, a ``DataFrame`` is returned. When concatenating along
    the columns (axis=1), a ``DataFrame`` is returned.

See Also
--------
DataFrame.join : Join DataFrames using indexes.
DataFrame.merge : Merge DataFrames by indexes or columns.

Notes
-----
The keys, levels, and names arguments are all optional.

A walkthrough of how this method fits in with other tools for combining
pandas objects can be found `here
<https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html>`__.

It is not recommended to build DataFrames by adding single rows in a
for loop. Build a list of rows and make a DataFrame in a single concat.

Examples
--------
Combine two ``Series``.

>>> s1 = pd.Series(['a', 'b'])
>>> s2 = pd.Series(['c', 'd'])
>>> pd.concat([s1, s2])
0    a
1    b
0    c
1    d
dtype: object

Clear the existing index and reset it in the result
by setting the ``ignore_index`` option to ``True``.

>>> pd.concat([s1, s2], ignore_index=True)
0    a
1    b
2    c
3    d
dtype: object

Add a hierarchical index at the outermost level of
the data with the ``keys`` option.

>>> pd.concat([s1, s2], keys=['s1', 's2'])
s1  0    a
    1    b
s2  0    c
    1    d
dtype: object

Label the index keys you create with the ``names`` option.

>>> pd.concat([s1, s2], keys=['s1', 's2'],
...           names=['Series name', 'Row ID'])
Series name  Row ID
s1           0         a
             1         b
s2           0         c
             1         d
dtype: object

Combine two ``DataFrame`` objects with identical columns.

>>> df1 = pd.DataFrame([['a', 1], ['b', 2]],
...                    columns=['letter', 'number'])
>>> df1
  letter  number
0      a       1
1      b       2
>>> df2 = pd.DataFrame([['c', 3], ['d', 4]],
...                    columns=['letter', 'number'])
>>> df2
  letter  number
0      c       3
1      d       4
>>> pd.concat([df1, df2])
  letter  number
0      a       1
1      b       2
0      c       3
1      d       4

Combine ``DataFrame`` objects with overlapping columns
and return everything. Columns outside the intersection will
be filled with ``NaN`` values.

>>> df3 = pd.DataFrame([['c', 3, 'cat'], ['d', 4, 'dog']],
...                    columns=['letter', 'number', 'animal'])
>>> df3
  letter  number animal
0      c       3    cat
1      d       4    dog
>>> pd.concat([df1, df3], sort=False)
  letter  number animal
0      a       1    NaN
1      b       2    NaN
0      c       3    cat
1      d       4    dog

Combine ``DataFrame`` objects with overlapping columns
and return only those that are shared by passing ``inner`` to
the ``join`` keyword argument.

>>> pd.concat([df1, df3], join="inner")
  letter  number
0      a       1
1      b       2
0      c       3
1      d       4

Combine ``DataFrame`` objects horizontally along the x axis by
passing in ``axis=1``.

>>> df4 = pd.DataFrame([['bird', 'polly'], ['monkey', 'george']],
...                    columns=['animal', 'name'])
>>> pd.concat([df1, df4], axis=1)
  letter  number  animal    name
0      a       1    bird   polly
1      b       2  monkey  george

Prevent the result from including duplicate index values with the
``verify_integrity`` option.

>>> df5 = pd.DataFrame([1], index=['a'])
>>> df5
   0
a  1
>>> df6 = pd.DataFrame([2], index=['a'])
>>> df6
   0
a  2
>>> pd.concat([df5, df6], verify_integrity=True)
Traceback (most recent call last):
    ...
ValueError: Indexes have overlapping values: ['a']

Append a single row to the end of a ``DataFrame`` object.

>>> df7 = pd.DataFrame({'a': 1, 'b': 2}, index=[0])
>>> df7
    a   b
0   1   2
>>> new_row = pd.Series({'a': 3, 'b': 4})
>>> new_row
a    3
b    4
dtype: int64
>>> pd.concat([df7, new_row.to_frame().T], ignore_index=True)
    a   b
0   1   2
1   3   4
File:      c:\users\lenovo\anaconda3\lib\site-packages\pandas\core\reshape\concat.py
Type:      function

In [109]:
pd.concat([df1,df2],ignore_index=False)

   var1  var2  var3
0     9    22    27
1     2     8    23
2    15    25    21
3     5    10    17
4     2    19     4
0   108   121   126
1   101   107   122
2   114   124   120
3   104   109   116
4   101   118   103

In [111]:
pd.concat([df1,df2],ignore_index=True)

   var1  var2  var3
0     9    22    27
1     2     8    23
2    15    25    21
3     5    10    17
4     2    19     4
5   108   121   126
6   101   107   122
7   114   124   120
8   104   109   116
9   101   118   103

In [115]:
df1.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [117]:
df2.columns = ["var1","var2","deg3"]

In [119]:
df2.columns

Index(['var1', 'var2', 'deg3'], dtype='object')

In [121]:
df2

   var1  var2  deg3
0   108   121   126
1   101   107   122
2   114   124   120
3   104   109   116
4   101   118   103

In [123]:
df1

   var1  var2  var3
0     9    22    27
1     2     8    23
2    15    25    21
3     5    10    17
4     2    19     4

In [127]:
pd.concat([df1,df2]) # var3 df2 de karsılıgı yok aynı skeılde deg3 de df1 de karsılıgı yok

   var1  var2  var3   deg3
0     9    22  27.0    NaN
1     2     8  23.0    NaN
2    15    25  21.0    NaN
3     5    10  17.0    NaN
4     2    19   4.0    NaN
0   108   121   NaN  126.0
1   101   107   NaN  122.0
2   114   124   NaN  120.0
3   104   109   NaN  116.0
4   101   118   NaN  103.0

In [129]:
pd.concat([df1,df2], join="inner") #kesisimlere gore birleştirdi

   var1  var2
0     9    22
1     2     8
2    15    25
3     5    10
4     2    19
0   108   121
1   101   107
2   114   124
3   104   109
4   101   118

# ileri birleştirme islemleri

In [160]:
import pandas as pd
import numpy as np

df1 = pd.DataFrame({"calisanlar": ["Ali","Veli","Ayse","Fatma"],"grup":["Muhasebe","Muhendislik","Muhendislik","İK"]})
df1

  calisanlar         grup
0        Ali     Muhasebe
1       Veli  Muhendislik
2       Ayse  Muhendislik
3      Fatma           İK

In [166]:
df2 = pd.DataFrame({"calisanlar":["Ayse","Ali","Veli","Fatma"],"ilk_giris":[2010,2009,2014,2019]})
df2

  calisanlar  ilk_giris
0       Ayse       2010
1        Ali       2009
2       Veli       2014
3      Fatma       2019

In [168]:
pd.merge(df1,df2) # merge bire bir birleştirme default olarak calisanlar ortak oldugu icin calisanlara göre birleştirdi

  calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           İK       2019

In [177]:
pd.merge(df1,df2, on="calisanlar")

  calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           İK       2019

In [179]:
# coktan tekile many to one
df3 = pd.merge(df1,df2)
df3

  calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           İK       2019

In [183]:
df4 = pd.DataFrame({"grup":["Muhasebe","Muhendislik","İK"],"mudur":["Caner","Mustafa","Berkcan"]})
df4

          grup    mudur
0     Muhasebe    Caner
1  Muhendislik  Mustafa
2           İK  Berkcan

In [185]:
pd.merge(df3,df4)

  calisanlar         grup  ilk_giris    mudur
0        Ali     Muhasebe       2009    Caner
1       Veli  Muhendislik       2014  Mustafa
2       Ayse  Muhendislik       2010  Mustafa
3      Fatma           İK       2019  Berkcan

In [187]:
# many to many coktan coka
df5 = pd.DataFrame({"grup":["Muhasebe","Muhasebe","Muhendislik","Muhendislik","İK","İK"],"yetenekler":["matematik","excel","kodlama","linux","excel","yonetim"]})
df5

          grup yetenekler
0     Muhasebe  matematik
1     Muhasebe      excel
2  Muhendislik    kodlama
3  Muhendislik      linux
4           İK      excel
5           İK    yonetim

In [189]:
df1

  calisanlar         grup
0        Ali     Muhasebe
1       Veli  Muhendislik
2       Ayse  Muhendislik
3      Fatma           İK

In [191]:
pd.merge(df1,df5) # her calısanın yeteneklerini belirtir

  calisanlar         grup yetenekler
0        Ali     Muhasebe  matematik
1        Ali     Muhasebe      excel
2       Veli  Muhendislik    kodlama
3       Veli  Muhendislik      linux
4       Ayse  Muhendislik    kodlama
5       Ayse  Muhendislik      linux
6      Fatma           İK      excel
7      Fatma           İK    yonetim