# Gruplama ve Toplulaştırma (Grouping & Aggregation )
## Basit toplulaştırma
- count()
 - first()
 - last()
 - mean()
 - median()
 - min()
 - max()
 - std()
 - var()
 - sum()

## Veri seti ile ugrasiken ilk fonksiyonalr bunlardır.

In [13]:
import seaborn as sns

In [25]:
df = sns.load_dataset("planets")

In [21]:
?sns.load_dataset # veri setleri adresi

Signature: sns.load_dataset(name, cache=True, data_home=None, **kws)
Docstring:
Load an example dataset from the online repository (requires internet).

This function provides quick access to a small number of example datasets
that are useful for documenting seaborn or generating reproducible examples
for bug reports. It is not necessary for normal usage.

Note that some of the datasets have a small amount of preprocessing applied
to define a proper ordering for categorical variables.

Use :func:`get_dataset_names` to see a list of available datasets.

Parameters
----------
name : str
    Name of the dataset (``{name}.csv`` on
    https://github.com/mwaskom/seaborn-data).
cache : boolean, optional
    If True, try to load from the local cache first, and save to the cache
    if a download is required.
data_home : string, optional
    The directory in which to cache data; see :func:`get_data_home`.
kws : keys and values, optional
    Additional keyword arguments are passed to passed through to
    :func:`pandas.read_csv`.

Returns
-------
df : :class:`pandas.DataFrame`
    Tabular data, possibly with some preprocessing applied.
File:      c:\users\lenovo\anaconda3\lib\site-packages\seaborn\utils.py
Type:      function

In [27]:
df.head() # ilk 5 veri

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [29]:
df.shape

(1035, 6)

In [41]:
df["mass"].mean()

2.6381605847953216

In [43]:
df["mass"].count()

513

In [45]:
df["mass"].min()

0.0036

In [47]:
df["mass"].max()

25.0

In [49]:
df["mass"].sum()

1353.37638

In [51]:
df["mass"].std()

3.8186166509616046

In [53]:
df["mass"].var()

14.58183312700122

In [55]:
df.describe() # betimsel/ tanımlama istatistiklerle tablo halinde görebiliriz

            number  orbital_period        mass     distance         year
count  1035.000000      992.000000  513.000000   808.000000  1035.000000
mean      1.785507     2002.917596    2.638161   264.069282  2009.070531
std       1.240976    26014.728304    3.818617   733.116493     3.972567
min       1.000000        0.090706    0.003600     1.350000  1989.000000
25%       1.000000        5.442540    0.229000    32.560000  2007.000000
50%       1.000000       39.979500    1.260000    55.250000  2010.000000
75%       2.000000      526.005000    3.040000   178.500000  2012.000000
max       7.000000   730000.000000   25.000000  8500.000000  2014.000000

In [57]:
df.describe().T # transpoz ile daha okunabilir bir tablo elde ederiz

,count,mean,std,min,25%,50%,75%,max
number,1035.0,1.785507,1.240976,1.000000,1.00000,1.0000,2.000,7.0
orbital_period,992.0,2002.917596,26014.728304,0.090706,5.44254,39.9795,526.005,730000.0
mass,513.0,2.638161,3.818617,0.003600,0.22900,1.2600,3.040,25.0
distance,808.0,264.069282,733.116493,1.350000,32.56000,55.2500,178.500,8500.0
year,1035.0,2009.070531,3.972567,1989.000000,2007.00000,2010.0000,2012.000,2014.0

In [61]:
df.dropna().describe().T # tanımlanmayan / eksik degerler varsa

,count,mean,std,min,25%,50%,75%,max
number,498.0,1.734940,1.175720,1.0000,1.00000,1.000,2.0000,6.0
orbital_period,498.0,835.778671,1469.128259,1.3283,38.27225,357.000,999.6000,17337.5
mass,498.0,2.509320,3.636274,0.0036,0.21250,1.245,2.8675,25.0
distance,498.0,52.068213,46.596041,1.3500,24.49750,39.940,59.3325,354.0
year,498.0,2007.377510,4.167284,1989.0000,2005.00000,2009.000,2011.0000,2014.0

# Gruplama işlemleri

In [70]:
import pandas as pd
df = pd.DataFrame({"gruplar":["A","B","C","A","B","C"],"veri":[10,11,52,23,43,55]},columns=["gruplar","veri"])
df

  gruplar  veri
0       A    10
1       B    11
2       C    52
3       A    23
4       B    43
5       C    55

In [72]:
df.groupby("gruplar") # grupları tutar

In [74]:
df.groupby("gruplar").mean() # tutulan grupların ortalamasını al

         veri
gruplar
A        16.5
B        27.0
C        53.5

In [76]:
df.groupby("gruplar").sum()

         veri
gruplar
A          33
B          54
C         107

In [78]:
df.groupby("gruplar").count()

         veri
gruplar
A           2
B           2
C           2

In [80]:
import seaborn as sns
df = sns.load_dataset("planets")

In [82]:
df.head()

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [88]:
df.groupby("method") # method grubunu yakaladı

In [90]:
df.groupby("method")["orbital_period"] # grup metod gore grupladı orbital_period degiskenine secti

In [92]:
df.groupby("method")["orbital_period"].mean() # metod yakaladı burda metod gruplarına karsılık gelen orbital_period degiskenini yakaladı. ortalamasını aldı

method
Astrometry                          631.180000
Eclipse Timing Variations          4751.644444
Imaging                          118247.737500
Microlensing                       3153.571429
Orbital Brightness Modulation         0.709307
Pulsar Timing                      7343.021201
Pulsation Timing Variations        1170.000000
Radial Velocity                     823.354680
Transit                              21.102073
Transit Timing Variations            79.783500
Name: orbital_period, dtype: float64

In [96]:
df.groupby("method")["mass"].mean()

method
Astrometry                            NaN
Eclipse Timing Variations        5.125000
Imaging                               NaN
Microlensing                          NaN
Orbital Brightness Modulation         NaN
Pulsar Timing                         NaN
Pulsation Timing Variations           NaN
Radial Velocity                  2.630699
Transit                          1.470000
Transit Timing Variations             NaN
Name: mass, dtype: float64

In [98]:
df.groupby("method")["mass"].describe()

,count,mean,std,min,25%,50%,75%,max
method,,,,,,,,
Astrometry,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Eclipse Timing Variations,2.0,5.125000,1.308148,4.2000,4.66250,5.125,5.5875,6.05
Imaging,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Microlensing,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Orbital Brightness Modulation,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Pulsar Timing,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Pulsation Timing Variations,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Radial Velocity,510.0,2.630699,3.825883,0.0036,0.22525,1.260,3.0000,25.00
Transit,1.0,1.470000,NaN,1.4700,1.47000,1.470,1.4700,1.47
Transit Timing Variations,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [100]:
df.groupby("method")["mass"].describe().T

method,Astrometry,Eclipse Timing Variations,Imaging,Microlensing,Orbital Brightness Modulation,Pulsar Timing,Pulsation Timing Variations,Radial Velocity,Transit,Transit Timing Variations
count,0.0,2.000000,0.0,0.0,0.0,0.0,0.0,510.000000,1.00,0.0
mean,NaN,5.125000,NaN,NaN,NaN,NaN,NaN,2.630699,1.47,NaN
std,NaN,1.308148,NaN,NaN,NaN,NaN,NaN,3.825883,NaN,NaN
min,NaN,4.200000,NaN,NaN,NaN,NaN,NaN,0.003600,1.47,NaN
25%,NaN,4.662500,NaN,NaN,NaN,NaN,NaN,0.225250,1.47,NaN
50%,NaN,5.125000,NaN,NaN,NaN,NaN,NaN,1.260000,1.47,NaN
75%,NaN,5.587500,NaN,NaN,NaN,NaN,NaN,3.000000,1.47,NaN
max,NaN,6.050000,NaN,NaN,NaN,NaN,NaN,25.000000,1.47,NaN

In [102]:
df.dropna().groupby("method")["mass"].describe().T

method  Radial Velocity  Transit
count        497.000000     1.00
mean           2.511411     1.47
std            3.639638      NaN
min            0.003600     1.47
25%            0.210000     1.47
50%            1.240000     1.47
75%            2.880000     1.47
max           25.000000     1.47

In [142]:
# aggregate, filter, transform, apply --< ileri seviye veri analizinde kullanılan fonksiyonlar
import pandas as pd
df = pd.DataFrame({"gruplar":["A","B","C","A","B","C"],"degisken1":[10,23,33,22,11,99],"degisken2":[100,253,333,262,111,969]},columns=["gruplar","degisken1","degisken2"])
df

  gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [144]:
# aggregate
df.groupby("gruplar").mean() # gruplara gore ortalama hesaplar. veri setini gruplara göre böl

         degisken1  degisken2
gruplar
A             16.0      181.0
B             17.0      182.0
C             66.0      651.0

In [146]:
import numpy as np
df.groupby("gruplar").aggregate([min,np.median,max])

C:\Users\lenovo\AppData\Local\Temp\ipykernel_16748\1358696741.py:2: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df.groupby("gruplar").aggregate([min,np.median,max])
C:\Users\lenovo\AppData\Local\Temp\ipykernel_16748\1358696741.py:2: FutureWarning: The provided callable <function median at 0x000001676958F880> is currently using SeriesGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  df.groupby("gruplar").aggregate([min,np.median,max])
C:\Users\lenovo\AppData\Local\Temp\ipykernel_16748\1358696741.py:2: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df.groupby("gruplar").aggregate([min,np.median,max])
C:\Users\lenovo\AppData\Local\Temp\ipykernel_16748\1358696741.py:2: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df.groupby("gruplar").aggregate([min,np.median,max])

        degisken1            degisken2
              min median max       min median  max
gruplar
A              10   16.0  22       100  181.0  262
B              11   17.0  23       111  182.0  253
C              33   66.0  99       333  651.0  969

In [149]:
df.groupby("gruplar").aggregate({"degisken1":"min","degisken2":"max"})
# gruplara göre böl aggregate ile degisken1 icin min degisken2 icin max bul

         degisken1  degisken2
gruplar
A               10        262
B               11        253
C               33        969

In [151]:
# filter klasik filtrelemerde kosul calıstırırız. mevcut pandas fonk bu kosul yok ç fonk kendimiz tanımlamamız gerekiyor
import pandas as pd
df = pd.DataFrame({"gruplar":["A","B","C","A","B","C"],"degisken1":[10,23,33,22,11,99],"degisken2":[100,253,333,262,111,969]},columns=["gruplar","degisken1","degisken2"])
df

  gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [153]:
def filter_func(x):
    return x["degisken1"].std() >9

In [159]:
df.groupby("gruplar").std()

         degisken1   degisken2
gruplar
A         8.485281  114.551299
B         8.485281  100.409163
C        46.669048  449.719913

In [161]:
df.groupby("gruplar").filter(filter_func)

  gruplar  degisken1  degisken2
2       C         33        333
5       C         99        969

In [163]:
# transform desıskenlerde donusturme / degisiklik

df["degisken1"]*9

0     90
1    207
2    297
3    198
4     99
5    891
Name: degisken1, dtype: int64

In [175]:
df_a = df.iloc[:,1:3]
df_a

   degisken1  degisken2
0         10        100
1         23        253
2         33        333
3         22        262
4         11        111
5         99        969

In [181]:
# tanımlı bir fonk yoksa biz degisiklik yapabiliriz
df_a.transform(lambda x: (x-x.mean())/x.std()) #butun degiskenlerde degiisklik yapar

   degisken1  degisken2
0  -0.687871  -0.738461
1  -0.299074  -0.263736
2   0.000000  -0.015514
3  -0.328982  -0.235811
4  -0.657963  -0.704331
5   1.973890   1.957853

In [183]:
df_a

   degisken1  degisken2
0         10        100
1         23        253
2         33        333
3         22        262
4         11        111
5         99        969

In [217]:
# apply
import pandas as pd
df = pd.DataFrame({"gruplar":["A","B","C","A","B","C"],"degisken1":[10,23,33,22,11,99],"degisken2":[100,253,333,262,111,969]},columns=["gruplar","degisken1","degisken2"])
df

  gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [219]:
df.groupby("gruplar").apply(np.sum)

C:\Users\lenovo\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
C:\Users\lenovo\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
C:\Users\lenovo\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
C:\Users\lenovo\AppData\Local\Temp\ipykernel_16748\2155945059.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby("gruplar").apply(np.sum)

        gruplar  degisken1  degisken2
gruplar
A            AA         32        362
B            BB         34        364
C            CC        132       1302

In [223]:
df.groupby("gruplar").apply(np.mean)

gruplar
A     98.5
B     99.5
C    358.5
dtype: float64