# Pivot Table

In [6]:
import pandas as pd
import numpy as np
import seaborn as sns

titanic = sns.load_dataset("titanic")
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [8]:
titanic.groupby("sex")["survived"].mean() # sag kalanların ortalaması

sex
female    0.742038
male      0.188908
Name: survived, dtype: float64

In [10]:
titanic.groupby("sex")[["survived"]].mean() # sag kalanların ortalaması

        survived
sex
female  0.742038
male    0.188908

In [17]:
titanic.groupby(["sex","class"])[["survived"]].aggregate("mean")
# kadınlardan first second third class da yasayanlardan yuzde kacı kurtulmus
# benzer sekilde erkeklerden first second an dthird class yuzde kacı kurtulmus

C:\Users\lenovo\AppData\Local\Temp\ipykernel_2468\3549703915.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  titanic.groupby(["sex","class"])[["survived"]].aggregate("mean")

               survived
sex    class
female First   0.968085
       Second  0.921053
       Third   0.500000
male   First   0.368852
       Second  0.157407
       Third   0.135447

In [19]:
titanic.groupby(["sex","class"])[["survived"]].aggregate("mean").unstack() # unstack() okumayı daha kolay olmasını saglar

C:\Users\lenovo\AppData\Local\Temp\ipykernel_2468\2203689429.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  titanic.groupby(["sex","class"])[["survived"]].aggregate("mean").unstack()

        survived
class      First    Second     Third
sex
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [37]:
# pivot ile pivot table

titanic.pivot_table("survived",index="sex",columns="class")
# odaklanan degisken ""survived
# index =sex  satır olarak degerlendiriyor
# class degiskenine de odaklan stunlara class olarak atanır

C:\Users\lenovo\AppData\Local\Temp\ipykernel_2468\956352716.py:3: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  titanic.pivot_table("survived",index="sex",columns="class")

class      First    Second     Third
sex
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [39]:
titanic.age.head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: age, dtype: float64

In [47]:
age = pd.cut(titanic["age"],[0,18,90])
# titanic verisindeki age degiskenini bol. 0, 18,90 degerlerine göre bol
age.head(10)

0    (18.0, 90.0]
1    (18.0, 90.0]
2    (18.0, 90.0]
3    (18.0, 90.0]
4    (18.0, 90.0]
5             NaN
6    (18.0, 90.0]
7     (0.0, 18.0]
8    (18.0, 90.0]
9     (0.0, 18.0]
Name: age, dtype: category
Categories (2, interval[int64, right]): [(0, 18] < (18, 90]]

In [49]:
titanic.pivot_table("survived",["sex",age],"class")

C:\Users\lenovo\AppData\Local\Temp\ipykernel_2468\350991148.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  titanic.pivot_table("survived",["sex",age],"class")

class               First    Second     Third
sex    age
female (0, 18]   0.909091  1.000000  0.511628
       (18, 90]  0.972973  0.900000  0.423729
male   (0, 18]   0.800000  0.600000  0.215686
       (18, 90]  0.375000  0.071429  0.133663