In [59]:
import pandas as pd

In [61]:
pd.read_csv("reading_data/ornekcsv.csv") # duzgun okunmadı

       a;b;c
0    78;12;1
1    78;12;2
2   78;324;3
3      7;2;4
4    88;23;5
5       6;2;
6    56;11;6
7     7;12;7
8    56;21;7
9    346;2;8
10     5;1;8
11  456;21;8
12   3;12;88

In [63]:
# csv sep=";" gore ayıyarak okudu
pd.read_csv("reading_data/ornekcsv.csv",sep=";")

      a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [65]:
# txt okuma
pd.read_csv("reading_data/duz_metin.txt")

    1 2
0   2 2
1   3 2
2   4 2
3   5 2
4   6 2
5  7 2
6   8 2
7   9 2
8  10 2

In [69]:
df = pd.read_excel("reading_data/ornekx.xlsx")

In [71]:
type(df)

pandas.core.frame.DataFrame

In [73]:
df.head()

    a    b    c
0  78   12  1.0
1  78   12  2.0
2  78  324  3.0
3   7    2  4.0
4  88   23  5.0

In [79]:
df.columns

Index(['a', 'b', 'c'], dtype='object')

In [81]:
df.columns = ("A","B","C")
df.columns

Index(['A', 'B', 'C'], dtype='object')