# Boxplot
## Veri seti hikayesi

In [2]:
import seaborn as sns
tips = sns.load_dataset("tips")
df = tips.copy()
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [4]:
df.describe().T

            count       mean       std   min      25%     50%      75%    max
total_bill  244.0  19.785943  8.902412  3.07  13.3475  17.795  24.1275  50.81
tip         244.0   2.998279  1.383638  1.00   2.0000   2.900   3.5625  10.00
size        244.0   2.569672  0.951100  1.00   2.0000   2.000   3.0000   6.00

In [6]:
df["sex"].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [12]:
df["smoker"].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [14]:
df["day"].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [16]:
df["time"].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [3]:
import seaborn as sns
tips = sns.load_dataset("tips")
df = tips.copy()
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
sns.boxplot(x = df["total_bill"])

# Çaprazlamalar

In [1]:
import seaborn as sns
tips = sns.load_dataset("tips")
df = tips.copy()
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [8]:
df.describe().T

            count       mean       std   min      25%     50%      75%    max
total_bill  244.0  19.785943  8.902412  3.07  13.3475  17.795  24.1275  50.81
tip         244.0   2.998279  1.383638  1.00   2.0000   2.900   3.5625  10.00
size        244.0   2.569672  0.951100  1.00   2.0000   2.000   3.0000   6.00

In [ ]:
# Hangi gunler daha fazla kazanıyoruz

sns.boxplot(x="day",y="total_bill",data=df)

In [3]:
# sabah mı aksam kı daha çok kazanıyoruz?

In [ ]:
sns.boxplot(x="time",y="total_bill",data=df)

In [3]:
# kisi sayısı kazanc

In [ ]:
sns.boxplot(x="size",y="total_bill",data=df)

In [1]:
# gun cinsiyet odenne hesaplar

In [3]:
sns.boxplot(x="day",y="total_bill", hue="sex",data=df)

NameError: name 'sns' is not defined